#
# Copyright (C) 2015 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for ASIC and FPGA Miner for Bitcoin
LUCI_DEPENDS:=+cgminer +cgminer_monitor +luasocket

PKG_MAINTAINER:=Libor Vasicek <libor.vasicek@braiins.cz>
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
